### ISSUE TITLE
it's not Issue. just i have some questions.

### ISSUE THREAD

**Issue by pervin0527** [SCRN-VRC/YOLOv4-Tiny-in-UnityCG-HLSL#1]
Hi. I am very impressed with what you made.
actually, I'm also trying to get yolov4-tiny to work in unity.
However, I think UNITY will have difficulties because it is my first time using it.

I converted the yolov4 model trained on darknet to onnx.
And then I uploaded it to unity, but I can't seem to read the model file.
Like I said, I know very little about unity.

So, I'd like you to explain the tutorial or process of applying yolov4 to unity. Can you do that?

**Comment by SCRN-VRC** [comment]
I wrote the network architecture by hand by comparing each output layers one by one from the actual tensorflow output. Unless you need to do it this way, I suggest using [Barracuda](https://docs.unity3d.com/Packages/com.unity.barracuda@1.0/manual/index.html), a neural network library for Unity. They have a few examples including YoloV2 tiny.

https://github.com/keijiro/TinyYOLOv2Barracuda

**Comment by pervin0527** [comment]
Thanks for the reply!
Q1. I read about barracuda too. But it seems that only yolov2 or v3 can be used. Isn't that??  

    When exporting from TensorFlow or Keras, use TF-1 instead of TF-2.

This is the phrase written in the official barracuda [manual](https://docs.unity3d.com/Packages/com.unity.barracuda@1.4/manual/Exporting.html#tensorflow).
It seems to me that the operations supported by tensorflow 2 are not possible in unity....

Q2. I looked for another way, and this is a c# based tensorflow. 
[Tensorflow.NET](https://github.com/SciSharp/TensorFlow.NET)
So, integrate Tensorflow.NET and UNITY, and I'm trying to use my yolov4 model.
I think it's better to do this than barracuda. What do you think?

**Comment by SCRN-VRC** [comment]
Yea barracuda's pretty limited compared to the other libraries. You can try importing external C# libraries into unity, not sure how much of that is documented. Or you can keep unity out of the equation until you actually need it like building everything in an external program that unity just calls.

**Comment by pervin0527** [comment]
Okay i really really appreciate to your advise!!
I will try and review the compatibility work through tensorflow.NET. Thank you so much and hope you have a good day!
