### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by FerLuisxd** [SCRN-VRC/YOLOv4-Tiny-in-UnityCG-HLSL#2]
How long did it took to train the Yolov4 tiny? Also what pc setups are you guys using?

**Comment by SCRN-VRC** [comment]
I didn't have to train it, the pre trained model is provided for you here

https://github.com/WongKinYiu/ScaledYOLOv4/tree/yolov4-tiny

People then convert the model and weights into whatever ML library they wanna use it with, like PyTorch or TensorFlow. For this implementation I had to recreate the model from scratch in HLSL. And the weights I just converted into a format I can use.

PC wise I'm still on a 1800X and 1080TI.
